CPPC = g++
CPPFLAGS = -Wall -O2
TARGET = guess-my-name my-name-guesser


all: guess-my-name my-name-guesser

guess-my-name: guess-my-name.cpp
	$(CPPC) $(CPPFLAGS) -o $@ guess-my-name.cpp

my-name-guesser: my-name-guesser.cpp
	$(CPPC) $(CPPFLAGS) -o $@ my-name-guesser.cpp